sudo: false

language: java
jdk:
  - oraclejdk11
  - oraclejdk12
  
before_install:
  - "export DISPLAY=:99.0"
  - "export TERM=dumb"
  - "sh -e /etc/init.d/xvfb start"

install:
    - TERM=dumb ./gradlew --refresh-dependencies --stacktrace

script:
    - TERM=dumb ./gradlew build --stacktrace

# after_failure:
#   - "cat ./build/test-results/*.xml"
